/// Flutter icons DSIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DSIcons
///      fonts:
///       - asset: fonts/DSIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

import 'ds_icon_data.dart';

// ignore_for_file: constant_identifier_names

class DSIcons {
  DSIcons._();

  static const IconData builder_quick_reply = DSIconData(0xe800);
  static const IconData text_style_italic = DSIconData(0xe801);
  static const IconData chart_line = DSIconData(0xe802);
  static const IconData arrow_down = DSIconData(0xe803);
  static const IconData arrow_ball_up = DSIconData(0xe804);
  static const IconData file_name_zip = DSIconData(0xe805);
  static const IconData file_name_doc = DSIconData(0xe806);
  static const IconData file_doc = DSIconData(0xe807);
  static const IconData file_java_script = DSIconData(0xe808);
  static const IconData file_gif = DSIconData(0xe809);
  static const IconData builder_router = DSIconData(0xe80a);
  static const IconData settings_adjusments = DSIconData(0xe80b);
  static const IconData arrow_ball_down = DSIconData(0xe80c);
  static const IconData file_empty_file = DSIconData(0xe80d);
  static const IconData file_txt = DSIconData(0xe80e);
  static const IconData message_received = DSIconData(0xe80f);
  static const IconData text_style_underline = DSIconData(0xe810);
  static const IconData file_name_txt = DSIconData(0xe811);
  static const IconData message_talk = DSIconData(0xe812);
  static const IconData arrow_first = DSIconData(0xe813);
  static const IconData arrow_right = DSIconData(0xe814);
  static const IconData builder_new_state = DSIconData(0xe815);
  static const IconData chart_pizza = DSIconData(0xe816);
  static const IconData text_style_bold = DSIconData(0xe817);
  static const IconData file_image = DSIconData(0xe818);
  static const IconData more_options_vertical = DSIconData(0xe819);
  static const IconData menu_hamburger = DSIconData(0xe81a);
  static const IconData file_image_expired = DSIconData(0xe81b);
  static const IconData settings_builder = DSIconData(0xe81c);
  static const IconData builder_text_message = DSIconData(0xe81d);
  static const IconData file_new = DSIconData(0xe81e);
  static const IconData more_options_horizontal = DSIconData(0xe81f);
  static const IconData arrow_filter_table = DSIconData(0xe820);
  static const IconData arrow_ball_right = DSIconData(0xe821);
  static const IconData file_video_expired = DSIconData(0xe822);
  static const IconData file_image_broken = DSIconData(0xe823);
  static const IconData file_name_xls = DSIconData(0xe824);
  static const IconData message_active = DSIconData(0xe825);
  static const IconData chart_bar = DSIconData(0xe826);
  static const IconData chart_column = DSIconData(0xe827);
  static const IconData message_sent = DSIconData(0xe828);
  static const IconData file_txt_1 = DSIconData(0xe829);
  static const IconData message_total = DSIconData(0xe82a);
  static const IconData message_ballon = DSIconData(0xe82b);
  static const IconData arrow_up = DSIconData(0xe82c);
  static const IconData builder_menu = DSIconData(0xe82d);
  static const IconData arrow_left = DSIconData(0xe82e);
  static const IconData file_name_csv = DSIconData(0xe82f);
  static const IconData menu_dot = DSIconData(0xe830);
  static const IconData file_csv = DSIconData(0xe831);
  static const IconData builder_test_bot = DSIconData(0xe832);
  static const IconData arrow_ball_left = DSIconData(0xe833);
  static const IconData builder_carrousel = DSIconData(0xe834);
  static const IconData arrow_last = DSIconData(0xe835);
  static const IconData file_name_ppt = DSIconData(0xe836);
  static const IconData builder_publish_bot = DSIconData(0xe837);
  static const IconData text_style_strikethrough = DSIconData(0xe838);
  static const IconData file_name_pdf = DSIconData(0xe839);
  static const IconData file_ppt = DSIconData(0xe83a);
  static const IconData file_pdf = DSIconData(0xe83b);
  static const IconData file_json = DSIconData(0xe83c);
  static const IconData localization = DSIconData(0xe83d);
  static const IconData link = DSIconData(0xe83e);
  static const IconData library_icon = DSIconData(0xe83f);
  static const IconData settings_general = DSIconData(0xe840);
  static const IconData channels = DSIconData(0xe841);
  static const IconData ab = DSIconData(0xe842);
  static const IconData debug = DSIconData(0xe843);
  static const IconData status = DSIconData(0xe844);
  static const IconData blip_tutorials = DSIconData(0xe845);
  static const IconData blip_ideas = DSIconData(0xe846);
  static const IconData share = DSIconData(0xe847);
  static const IconData payment_card = DSIconData(0xe848);
  static const IconData bill = DSIconData(0xe849);
  static const IconData barcode = DSIconData(0xe84a);
  static const IconData payment_card_cvc = DSIconData(0xe84b);
  static const IconData pix = DSIconData(0xe84c);
  static const IconData qrcode = DSIconData(0xe84d);
  static const IconData chip = DSIconData(0xe84e);
  static const IconData smartphone = DSIconData(0xe84f);
  static const IconData target = DSIconData(0xe850);
  static const IconData megaphone = DSIconData(0xe851);
  static const IconData folder = DSIconData(0xe852);
  static const IconData robot = DSIconData(0xe853);
  static const IconData ai = DSIconData(0xe854);
  static const IconData upload = DSIconData(0xe855);
  static const IconData save_disk = DSIconData(0xe856);
  static const IconData edit = DSIconData(0xe857);
  static const IconData trash = DSIconData(0xe858);
  static const IconData favorite = DSIconData(0xe859);
  static const IconData download = DSIconData(0xe85a);
  static const IconData order_elements = DSIconData(0xe85b);
  static const IconData deslike = DSIconData(0xe85c);
  static const IconData move = DSIconData(0xe85d);
  static const IconData save_flag = DSIconData(0xe85e);
  static const IconData like = DSIconData(0xe85f);
  static const IconData notes = DSIconData(0xe860);
  static const IconData search = DSIconData(0xe861);
  static const IconData audio = DSIconData(0xe862);
  static const IconData speaker = DSIconData(0xe863);
  static const IconData notebook = DSIconData(0xe864);
  static const IconData paperplane = DSIconData(0xe865);
  static const IconData mouse = DSIconData(0xe866);
  static const IconData airplane = DSIconData(0xe867);
  static const IconData add_persistent_menu = DSIconData(0xe868);
  static const IconData messenger = DSIconData(0xe869);
  static const IconData cloud = DSIconData(0xe86a);
  static const IconData filter = DSIconData(0xe86b);
  static const IconData attach = DSIconData(0xe86d);
  static const IconData resources = DSIconData(0xe86e);
  static const IconData delete = DSIconData(0xe86f);
  static const IconData integration = DSIconData(0xe870);
  static const IconData external_file = DSIconData(0xe871);
  static const IconData skills = DSIconData(0xe872);
  static const IconData camera = DSIconData(0xe873);
  static const IconData service_queue = DSIconData(0xe874);
  static const IconData bug_report = DSIconData(0xe875);
  static const IconData loading = DSIconData(0xe876);
  static const IconData primeiro_acesso = DSIconData(0xe877);
  static const IconData custom_channel = DSIconData(0xe878);
  static const IconData button = DSIconData(0xe879);
  static const IconData site = DSIconData(0xe87a);
  static const IconData copy = DSIconData(0xe87b);
  static const IconData close = DSIconData(0xe87c);
  static const IconData add = DSIconData(0xe87d);
  static const IconData true_icon = DSIconData(0xe87e);
  static const IconData plus = DSIconData(0xe87f);
  static const IconData trophy = DSIconData(0xe880);
  static const IconData conections = DSIconData(0xe881);
  static const IconData integrations_channels = DSIconData(0xe882);
  static const IconData book = DSIconData(0xe883);
  static const IconData air_balloon = DSIconData(0xe884);
  static const IconData emoji = DSIconData(0xe885);
  static const IconData mail = DSIconData(0xe886);
  static const IconData cloud_2 = DSIconData(0xe887);
  static const IconData keyboard = DSIconData(0xe888);
  static const IconData guide = DSIconData(0xe889);
  static const IconData paint = DSIconData(0xe88a);
  static const IconData plugin = DSIconData(0xe88b);
  static const IconData tag = DSIconData(0xe88c);
  static const IconData cookie = DSIconData(0xe88d);
  static const IconData ticket = DSIconData(0xe88e);
  static const IconData logout = DSIconData(0xe88f);
  static const IconData home = DSIconData(0xe890);
  static const IconData monitoring = DSIconData(0xe891);
  static const IconData screen_fill = DSIconData(0xe892);
  static const IconData screen_full = DSIconData(0xe893);
  static const IconData sso = DSIconData(0xe894);
  static const IconData user_engaged = DSIconData(0xe895);
  static const IconData team = DSIconData(0xe896);
  static const IconData agent = DSIconData(0xe897);
  static const IconData user_active = DSIconData(0xe898);
  static const IconData avatar_user = DSIconData(0xe899);
  static const IconData user_defaut = DSIconData(0xe89a);
  static const IconData contact = DSIconData(0xe89b);
  static const IconData checkball = DSIconData(0xe89c);
  static const IconData error = DSIconData(0xe89d);
  static const IconData voip = DSIconData(0xe89e);
  static const IconData faq = DSIconData(0xe89f);
  static const IconData false_icon = DSIconData(0xe8a0);
  static const IconData send = DSIconData(0xe8a1);
  static const IconData info = DSIconData(0xe8a2);
  static const IconData email = DSIconData(0xe8a3);
  static const IconData warning = DSIconData(0xe8a4);
  static const IconData bell = DSIconData(0xe8a5);
  static const IconData sms = DSIconData(0xe8a6);
  static const IconData attention = DSIconData(0xe8a7);
  static const IconData question = DSIconData(0xe8a8);
  static const IconData list = DSIconData(0xe8a9);
  static const IconData undo = DSIconData(0xe8aa);
  static const IconData restore = DSIconData(0xe8ab);
  static const IconData redo = DSIconData(0xe8ac);
  static const IconData refresh = DSIconData(0xe8ad);
  static const IconData priorization = DSIconData(0xe8ae);
  static const IconData transfer = DSIconData(0xe8af);
  static const IconData unlock = DSIconData(0xe8b0);
  static const IconData lock = DSIconData(0xe8b1);
  static const IconData eye_closed = DSIconData(0xe8b2);
  static const IconData data_security = DSIconData(0xe8b3);
  static const IconData eye_open = DSIconData(0xe8b4);
  static const IconData video = DSIconData(0xe8b5);
  static const IconData video_broken = DSIconData(0xe8b6);
  static const IconData xml = DSIconData(0xe8b7);
  static const IconData company = DSIconData(0xe8b8);
  static const IconData business = DSIconData(0xe8b9);
  static const IconData calendar = DSIconData(0xe8ba);
  static const IconData clock = DSIconData(0xe8bb);
  static const IconData date_time = DSIconData(0xe8bc);
  static const IconData redirect_solid = DSIconData(0xe8bd);
  static const IconData java_script_solid = DSIconData(0xe8be);
  static const IconData agent_rule_solid = DSIconData(0xe8bf);
  static const IconData variable_solid = DSIconData(0xe8c0);
  static const IconData http_solid = DSIconData(0xe8c1);
  static const IconData tracking_solid = DSIconData(0xe8c2);
  static const IconData level_up_solid = DSIconData(0xe8c3);
  static const IconData blip_forum_solid = DSIconData(0xe8c4);
  static const IconData bill_solid = DSIconData(0xe8c5);
  static const IconData barcode_solid = DSIconData(0xe8c6);
  static const IconData pix_solid = DSIconData(0xe8c7);
  static const IconData qrcode_solid = DSIconData(0xe8c8);
  static const IconData folder_solid = DSIconData(0xe8c9);
  static const IconData folder_save_solid = DSIconData(0xe8ca);
  static const IconData favorite_solid = DSIconData(0xe8cb);
  static const IconData save_solid = DSIconData(0xe8cc);
  static const IconData audio_solid = DSIconData(0xe8cd);
  static const IconData add_solid = DSIconData(0xe8ce);
  static const IconData checkball_solid = DSIconData(0xe8cf);
  static const IconData error_solid = DSIconData(0xe8d0);
  static const IconData voip_solid = DSIconData(0xe8d1);
  static const IconData send_solid = DSIconData(0xe8d2);
  static const IconData info_solid = DSIconData(0xe8d3);
  static const IconData email_solid = DSIconData(0xe8d4);
  static const IconData warning_solid = DSIconData(0xe8d5);
  static const IconData sms_solid = DSIconData(0xe8d6);
  static const IconData attention_solid = DSIconData(0xe8d7);
  static const IconData question_solid = DSIconData(0xe8d8);
  static const IconData left_ball_solid = DSIconData(0xe8d9);
  static const IconData right_ball_solid = DSIconData(0xe8da);
  static const IconData up_ball_solid = DSIconData(0xe8db);
  static const IconData down_ball_solid = DSIconData(0xe8dc);
  static const IconData blocks_solid = DSIconData(0xe8dd);
  static const IconData list_solid = DSIconData(0xe8de);
  static const IconData left_solid = DSIconData(0xe8df);
  static const IconData right_solid = DSIconData(0xe8e0);
  static const IconData filter_table_solid = DSIconData(0xe8e1);
  static const IconData up_solid = DSIconData(0xe8e2);
  static const IconData down_solid = DSIconData(0xe8e3);
  static const IconData video_solid = DSIconData(0xe8e4);
}
