// Flutter icons DSIcons
// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  DSIcons
//      fonts:
//       - asset: fonts/DSIcons.ttf
//
//
// * Material Design Icons, Copyright (C) Google, Inc
//         Author:    Google
//         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
//         Homepage:  https://design.google.com/icons/

import 'package:flutter/widgets.dart';

import 'ds_icon_data.dart';

// ignore_for_file: constant_identifier_names

class DSIcons {
  DSIcons._();

  static const IconData add_solid = DSIconData(0xe9d8);
  static const IconData agent_rule_solid = DSIconData(0xe9d9);
  static const IconData arrow_down_ball_solid = DSIconData(0xe9e1);
  static const IconData arrow_down_solid = DSIconData(0xe9e2);
  static const IconData arrow_left_ball_solid = DSIconData(0xe9ec);
  static const IconData arrow_left_solid = DSIconData(0xe9ed);
  static const IconData arrow_right_ball_solid = DSIconData(0xe9f3);
  static const IconData arrow_right_solid = DSIconData(0xe9f4);
  static const IconData arrow_up_ball_solid = DSIconData(0xe9f9);
  static const IconData arrow_up_solid = DSIconData(0xe9fa);
  static const IconData attention_solid = DSIconData(0xe9da);
  static const IconData audio_solid = DSIconData(0xe9db);
  static const IconData barcode_solid = DSIconData(0xe9dc);
  static const IconData bill_solid = DSIconData(0xe9dd);
  static const IconData blip_forum_solid = DSIconData(0xe9de);
  static const IconData blocks_solid = DSIconData(0xe9df);
  static const IconData checkball_solid = DSIconData(0xe9e0);
  static const IconData email_solid = DSIconData(0xe9e3);
  static const IconData error_solid = DSIconData(0xe9e4);
  static const IconData favorite_solid = DSIconData(0xe9e5);
  static const IconData filter_table_solid = DSIconData(0xe9e6);
  static const IconData folder_save_solid = DSIconData(0xe9e8);
  static const IconData folder_solid = DSIconData(0xe9e7);
  static const IconData http_solid = DSIconData(0xe9e9);
  static const IconData info_solid = DSIconData(0xe9ea);
  static const IconData java_script_solid = DSIconData(0xe9eb);
  static const IconData level_up_solid = DSIconData(0xe9d7);
  static const IconData list_solid = DSIconData(0xe9ee);
  static const IconData pix_solid = DSIconData(0xe9ef);
  static const IconData qrcode_solid = DSIconData(0xe9f0);
  static const IconData question_solid = DSIconData(0xe9f1);
  static const IconData redirect_solid = DSIconData(0xe9f2);
  static const IconData save_solid = DSIconData(0xe9f5);
  static const IconData send_solid = DSIconData(0xe9f6);
  static const IconData sms_solid = DSIconData(0xe9f7);
  static const IconData tracking_solid = DSIconData(0xe9f8);
  static const IconData variable_solid = DSIconData(0xe9fb);
  static const IconData video_solid = DSIconData(0xe9fc);
  static const IconData voip_solid = DSIconData(0xe9fd);
  static const IconData warning_solid = DSIconData(0xe9fe);
  static const IconData site_outline = DSIconData(0xe900);
  static const IconData ab_outline = DSIconData(0xe901);
  static const IconData add_outline = DSIconData(0xe902);
  static const IconData add_persistent_menu_outline = DSIconData(0xe903);
  static const IconData agent_outline = DSIconData(0xe904);
  static const IconData ai_outline = DSIconData(0xe905);
  static const IconData air_balloon_outline = DSIconData(0xe906);
  static const IconData airplane_outline = DSIconData(0xe907);
  static const IconData arrow_ball_down_outline = DSIconData(0xe908);
  static const IconData arrow_ball_left_outline = DSIconData(0xe909);
  static const IconData arrow_ball_right_outline = DSIconData(0xe90a);
  static const IconData arrow_ball_up_outline = DSIconData(0xe90b);
  static const IconData arrow_down_outline = DSIconData(0xe90c);
  static const IconData arrow_filter_table_outline = DSIconData(0xe90d);
  static const IconData arrow_first_outline = DSIconData(0xe90e);
  static const IconData arrow_last_outline = DSIconData(0xe90f);
  static const IconData arrow_left_outline = DSIconData(0xe910);
  static const IconData arrow_right_outline = DSIconData(0xe911);
  static const IconData arrow_up_outline = DSIconData(0xe912);
  static const IconData attach_outline = DSIconData(0xe913);
  static const IconData attention_outline = DSIconData(0xe914);
  static const IconData audio_outline = DSIconData(0xe915);
  static const IconData avatar_user_outline = DSIconData(0xe916);
  static const IconData barcode_outline = DSIconData(0xe917);
  static const IconData bell_outline = DSIconData(0xe918);
  static const IconData bill_outline = DSIconData(0xe919);
  static const IconData blip_ideas_outline = DSIconData(0xe91a);
  static const IconData blip_tutorials_outline = DSIconData(0xe91b);
  static const IconData book_outline = DSIconData(0xe91c);
  static const IconData bug_report_outline = DSIconData(0xe91e);
  static const IconData builder_carrousel_outline = DSIconData(0xe91f);
  static const IconData builder_menu_outline = DSIconData(0xe920);
  static const IconData builder_new_state_outline = DSIconData(0xe921);
  static const IconData builder_publish_bot_outline = DSIconData(0xe922);
  static const IconData builder_quick_reply_outline = DSIconData(0xe923);
  static const IconData builder_router_outline = DSIconData(0xe925);
  static const IconData builder_test_bot_outline = DSIconData(0xe926);
  static const IconData builder_text_message_outline = DSIconData(0xe928);
  static const IconData business_outline = DSIconData(0xe929);
  static const IconData button_outline = DSIconData(0xe92a);
  static const IconData calendar_outline = DSIconData(0xe92b);
  static const IconData camera_outline = DSIconData(0xe92c);
  static const IconData channels_outline = DSIconData(0xe92d);
  static const IconData chart_bar_outline = DSIconData(0xe92e);
  static const IconData chart_column_outline = DSIconData(0xe930);
  static const IconData chart_line_outline = DSIconData(0xe932);
  static const IconData chart_pizza_outline = DSIconData(0xe935);
  static const IconData check_outline = DSIconData(0xe937);
  static const IconData checkball_outline = DSIconData(0xe938);
  static const IconData chip_outline = DSIconData(0xe939);
  static const IconData clock_outline = DSIconData(0xe941);
  static const IconData close_outline = DSIconData(0xe942);
  static const IconData cloud_outline = DSIconData(0xe943);
  static const IconData cloud_2_outline = DSIconData(0xe944);
  static const IconData company_outline = DSIconData(0xe945);
  static const IconData conections_outline = DSIconData(0xe946);
  static const IconData contact_outline = DSIconData(0xe947);
  static const IconData cookie_outline = DSIconData(0xe948);
  static const IconData copy_outline = DSIconData(0xe949);
  static const IconData custom_channel_outline = DSIconData(0xe94a);
  static const IconData data_security_outline = DSIconData(0xe94b);
  static const IconData date_time_outline = DSIconData(0xe94c);
  static const IconData debug_outline = DSIconData(0xe94d);
  static const IconData delete_outline = DSIconData(0xe94e);
  static const IconData deslike_outline = DSIconData(0xe94f);
  static const IconData double_check_outline = DSIconData(0xe950);
  static const IconData download_outline = DSIconData(0xe951);
  static const IconData edit_outline = DSIconData(0xe952);
  static const IconData email_outline = DSIconData(0xe953);
  static const IconData emoji_outline = DSIconData(0xe954);
  static const IconData error_outline = DSIconData(0xe955);
  static const IconData external_file_outline = DSIconData(0xe956);
  static const IconData eye_closed_outline = DSIconData(0xe957);
  static const IconData eye_open_outline = DSIconData(0xe958);
  static const IconData false_outline = DSIconData(0xe959);
  static const IconData faq_outline = DSIconData(0xe95a);
  static const IconData favorite_outline = DSIconData(0xe95b);
  static const IconData file_csv_outline = DSIconData(0xe95c);
  static const IconData file_doc_outline = DSIconData(0xe95d);
  static const IconData file_empty_file_outline = DSIconData(0xe95e);
  static const IconData file_gif_outline = DSIconData(0xe95f);
  static const IconData file_image_outline = DSIconData(0xe960);
  static const IconData file_image_broken_outline = DSIconData(0xe961);
  static const IconData file_image_expired_outline = DSIconData(0xe962);
  static const IconData file_java_script_outline = DSIconData(0xe963);
  static const IconData file_json_outline = DSIconData(0xe964);
  static const IconData file_name_csv_outline = DSIconData(0xe965);
  static const IconData file_name_doc_outline = DSIconData(0xe966);
  static const IconData file_name_pdf_outline = DSIconData(0xe967);
  static const IconData file_name_ppt_outline = DSIconData(0xe968);
  static const IconData file_name_txt_outline = DSIconData(0xe969);
  static const IconData file_name_xls_outline = DSIconData(0xe96a);
  static const IconData file_name_zip_outline = DSIconData(0xe96b);
  static const IconData file_new_outline = DSIconData(0xe96c);
  static const IconData file_pdf_outline = DSIconData(0xe96d);
  static const IconData file_ppt_outline = DSIconData(0xe96e);
  static const IconData file_txt_outline = DSIconData(0xe96f);
  static const IconData file_txt_1_outline = DSIconData(0xe970);
  static const IconData file_video_expired_outline = DSIconData(0xe971);
  static const IconData filter_outline = DSIconData(0xe972);
  static const IconData folder_outline = DSIconData(0xe973);
  static const IconData guide_outline = DSIconData(0xe974);
  static const IconData home_outline = DSIconData(0xe977);
  static const IconData info_outline = DSIconData(0xe978);
  static const IconData integration_outline = DSIconData(0xe979);
  static const IconData integrations_channels_outline = DSIconData(0xe97a);
  static const IconData keyboard_outline = DSIconData(0xe97b);
  static const IconData less_outline = DSIconData(0xe97c);
  static const IconData library_outline = DSIconData(0xe97d);
  static const IconData like_outline = DSIconData(0xe97f);
  static const IconData link_outline = DSIconData(0xe980);
  static const IconData list_outline = DSIconData(0xe981);
  static const IconData loading_outline = DSIconData(0xe982);
  static const IconData localization_outline = DSIconData(0xe983);
  static const IconData lock_outline = DSIconData(0xe984);
  static const IconData logout_outline = DSIconData(0xe985);
  static const IconData mail_outline = DSIconData(0xe986);
  static const IconData megaphone_outline = DSIconData(0xe987);
  static const IconData menu_dot_outline = DSIconData(0xe988);
  static const IconData menu_hamburger_outline = DSIconData(0xe989);
  static const IconData message_active_outline = DSIconData(0xe98a);
  static const IconData message_ballon_outline = DSIconData(0xe98b);
  static const IconData message_received_outline = DSIconData(0xe98c);
  static const IconData message_sent_outline = DSIconData(0xe98d);
  static const IconData message_talk_outline = DSIconData(0xe98e);
  static const IconData message_total_outline = DSIconData(0xe98f);
  static const IconData messenger_outline = DSIconData(0xe991);
  static const IconData monitoring_outline = DSIconData(0xe992);
  static const IconData more_options_horizontal_outline = DSIconData(0xe994);
  static const IconData more_options_vertical_outline = DSIconData(0xe995);
  static const IconData mouse_outline = DSIconData(0xe996);
  static const IconData move_outline = DSIconData(0xe997);
  static const IconData notebook_outline = DSIconData(0xe998);
  static const IconData notes_outline = DSIconData(0xe999);
  static const IconData order_elements_outline = DSIconData(0xe99a);
  static const IconData paint_outline = DSIconData(0xe99b);
  static const IconData paperplane_outline = DSIconData(0xe99d);
  static const IconData payment_card_outline = DSIconData(0xe99e);
  static const IconData payment_card_cvc_outline = DSIconData(0xe99f);
  static const IconData pix_outline = DSIconData(0xe9a0);
  static const IconData plugin_outline = DSIconData(0xe9a1);
  static const IconData plus_outline = DSIconData(0xe9a2);
  static const IconData primeiro_acesso_outline = DSIconData(0xe9a3);
  static const IconData priorization_outline = DSIconData(0xe9a4);
  static const IconData qrcode_outline = DSIconData(0xe9a5);
  static const IconData question_outline = DSIconData(0xe9a6);
  static const IconData redo_outline = DSIconData(0xe9a7);
  static const IconData refresh_outline = DSIconData(0xe9a8);
  static const IconData refresh_pack_outline = DSIconData(0xe9a9);
  static const IconData resources_outline = DSIconData(0xe9aa);
  static const IconData restore_outline = DSIconData(0xe9ab);
  static const IconData robot_outline = DSIconData(0xe9ac);
  static const IconData save_disk_outline = DSIconData(0xe9ad);
  static const IconData save_flag_outline = DSIconData(0xe9ae);
  static const IconData screen_fill_outline = DSIconData(0xe9af);
  static const IconData screen_full_outline = DSIconData(0xe9b0);
  static const IconData search_outline = DSIconData(0xe9b1);
  static const IconData send_outline = DSIconData(0xe9b2);
  static const IconData service_queue_outline = DSIconData(0xe9b3);
  static const IconData settings_adjusments_outline = DSIconData(0xe9b4);
  static const IconData settings_builder_outline = DSIconData(0xe9b5);
  static const IconData settings_general_outline = DSIconData(0xe9b6);
  static const IconData share_outline = DSIconData(0xe9b7);
  static const IconData skills_outline = DSIconData(0xe9b8);
  static const IconData smartphone_outline = DSIconData(0xe9b9);
  static const IconData sms_outline = DSIconData(0xe9ba);
  static const IconData speaker_outline = DSIconData(0xe9bb);
  static const IconData sso_outline = DSIconData(0xe9bc);
  static const IconData status_outline = DSIconData(0xe9bd);
  static const IconData tag_outline = DSIconData(0xe9be);
  static const IconData target_outline = DSIconData(0xe9bf);
  static const IconData team_outline = DSIconData(0xe9c0);
  static const IconData text_style_bold_outline = DSIconData(0xe9c1);
  static const IconData text_style_italic_outline = DSIconData(0xe9c2);
  static const IconData text_style_strikethrough_outline = DSIconData(0xe9c3);
  static const IconData text_style_underline_outline = DSIconData(0xe9c4);
  static const IconData ticket_outline = DSIconData(0xe9c5);
  static const IconData time_passed_outline = DSIconData(0xe9c6);
  static const IconData transfer_outline = DSIconData(0xe9c7);
  static const IconData trash_outline = DSIconData(0xe9c8);
  static const IconData trophy_outline = DSIconData(0xe9c9);
  static const IconData true_outline = DSIconData(0xe9ca);
  static const IconData undo_outline = DSIconData(0xe9cb);
  static const IconData unlock_outline = DSIconData(0xe9cc);
  static const IconData upload_outline = DSIconData(0xe9cd);
  static const IconData user_active_outline = DSIconData(0xe9ce);
  static const IconData user_defaut_outline = DSIconData(0xe9cf);
  static const IconData user_engaged_outline = DSIconData(0xe9d0);
  static const IconData video_outline = DSIconData(0xe9d2);
  static const IconData video_broken_outline = DSIconData(0xe9d3);
  static const IconData voip_outline = DSIconData(0xe9d4);
  static const IconData warning_outline = DSIconData(0xe9d5);
  static const IconData xml_outline = DSIconData(0xe9d6);
}
