name: Merge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  merge-main-to-develop:
    name: Merge main back to develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge command
        run: |
            git fetch --unshallow
            git checkout develop
            git pull
            git merge --no-ff origin/main -m "build: merge main back to develop"
            git push