name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
    # with:
    #  working-directory: blip-ds-flutter/lib/blip_ds.dart
